deploy-test:
  tags:
    - test
    - shell
  stage: deploy
  before_script:
    - docker info
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
  script:
    - echo 'Deploying project to test...'
    - docker container ls -aq | xargs docker container stop
    - docker container ls -aq | xargs docker container rm
    - docker prune -f
    - docker compose up -d
    - echo 'Deploy completed. Running in' $(docker container ls -q)
  environment: test
