stages:
  - build
  - deploy

variables:
  IMAGE_NAME: happypiece/movie-catalog
  IMAGE_TAG: latest

lint:
  tags:
    - docker
  stage: build
  image:
    mcr.microsoft.com/dotnet/sdk:6.0
  script:
    - echo 'Linting project code...'
    - dotnet format --no-restore -v n
    - echo 'Lint completed'

build-image:
  tags:
    - build
    - docker
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - docker info
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
  script:
    - echo 'Building docker image...'
    # - docker rmi $(docker image ls -a | grep '$IMAGE_NAME')
    - docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
    - docker push ${IMAGE_NAME}:${IMAGE_TAG}
    - echo 'Build completed'

deploy:
  tags:
    - deploy
  stage: deploy
  before_script:
    - docker info
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
  script:
    - echo 'Deploying project...'
    - docker container ls -aq | xargs docker container stop
    - docker container ls -aq | xargs docker container rm
    - docker image ls -aq | xargs docker image rm -f
    - docker compose up -d
    - echo 'Deploy completed. Running in' $(docker container ls -q)
  environment: production