stages:
  - build
  - deploy

variables:
  IMAGE_NAME: happypiece/movie-catalog
  IMAGE_TAG: latest

build-image:
  image: docker:20.10.16
  stage: build
  tags:
    - build
  services:
    - docker:20.10.16-dind
  before_script:
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
  script:
    - docker image ls -aq | xargs docker image rm -f
    - docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
    - docker push ${IMAGE_NAME}:${IMAGE_TAG}

deploy:
  stage: deploy
  before_script:
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
  script:
    - docker container ls -aq | xargs docker container stop
    - docker container ls -aq | xargs docker container rm
    - docker image ls -aq | xargs docker image rm -f
    - docker compose up -d
  environment: production