stages:
  - build
  - deploy

build-image:
  stage: build
  variables:
    IMAGE_NAME: happypiece/movie-catalog
    IMAGE_TAG: latest
  before_script:
    - 'docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS'
  script:
    - docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
    - docker push ${IMAGE_NAME}:${IMAGE_TAG}

deploy:
  stage: deploy
  before_script:
    - 'docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS'
  script:
    - 'docker container ls -aq | xargs docker container stop'
    - 'docker container ls -aq | xargs docker container rm'
    - 'docker image ls -aq | xargs docker image rm -f'
    - 'docker compose up -d'
  environment: production