stages:
  - build
  - deploy
  - pages

variables:
  IMAGE_NAME: happypiece/movie-catalog
  IMAGE_TAG: latest

lint:
  tags:
    - docker
  stage: build
  image:
    mcr.microsoft.com/dotnet/sdk:6.0
  before_script:
    - dotnet --version
  script:
    - echo 'Linting project code...'
    - dotnet format --no-restore -v n
    - echo 'Lint completed'
  when: never


include: 
  - '.build-image-template.yml'
build-image:
  extends: .build-image-template
  when: never


deploy:
  tags:
    - deploy
  stage: deploy
  before_script:
    - docker info
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
  script:
    - echo 'Deploying project...'
    - docker container ls -aq | xargs docker container stop
    - docker container ls -aq | xargs docker container rm
    - docker image ls -aq | xargs docker image rm -f
    - docker compose up -d
    - echo 'Deploy completed. Running in' $(docker container ls -q)
  environment: production
  when: never

pages:
  rules:
  - if: $CI_PIPELINE_SOURCE == "push"
    changes:
      - /public/**/*
      - /public/*
    when: on_success
  stage: pages
  # needs: [build-image]
  allow_failure: true
  script:
    - echo 'Updating pages...'
  artifacts:
    paths:
      - /public/